### ISSUE TITLE
Not available on NetBeans dev versions in 'Tools > Plugins'

### ISSUE THREAD

**Issue by pmaselkowski** [markiewb/nb-close-other-projects#16]
Is it possible to make plugin available in NetBeans Plugin Portal Update Center on development versions of NetBeans? Tried at build 201609130002 but afaik on older builds it was also not available.

**Comment by markiewb** [comment]
There is no plugin center for Dev-versions. 
See https://benkiew.wordpress.com/2016/09/18/missing-plugins-for-your-netbeans-nightly-builds/
